=== k4si4G/Bryan-Cafe/branches.dtd
<!ELEMENT branches (branch+)>
<!ELEMENT branch (address, contact, openingHours)>
<!ELEMENT address (location, mapLink)>
<!ELEMENT location (#PCDATA)>
<!ELEMENT mapLink (#PCDATA)>
<!ELEMENT contact (#PCDATA)>
<!ELEMENT openingHours (weekday, weekend)>
<!ELEMENT weekday (#PCDATA)>
<!ELEMENT weekend (#PCDATA)>

=== k4si4G/Bryan-Cafe/branches.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE branches SYSTEM "branches.dtd">
<branches>
    <branch>
        <address>
            <location>
                76 Devonshire St, Surry Hills NSW 
            </location>
            <mapLink>https://maps.app.goo.gl/iDFDPRVzKLEk1GJP8</mapLink>
        </address>
        <contact>02 9211 1234</contact>
        <openingHours>
            <weekday>Mon - Fri: 6:00 to 14:30</weekday>
            <weekend>Sat-Sun: 7:00 to 15:00</weekend>
        </openingHours>
    </branch>
    <branch>
        <address>
            <location>
                451 Pitt St, Haymarket Sydney, NSW
            </location>
            <mapLink>https://maps.app.goo.gl/uMQAYJCdvRHu4HEr8</mapLink>
        </address>
        <contact>02 9262 5678</contact>
        <openingHours>
            <weekday>Mon - Fri: 6:00 to 16:00</weekday>
            <weekend>Sat-Sun: 7:00 to 15:00</weekend>
        </openingHours>
    </branch>
    <branch>
        <address>
            <location>
                31 Alfred Street, Circular Quay, NSW
            </location>
            <mapLink>https://maps.app.goo.gl/eZA4AJHBH7mncYoK6</mapLink>
        </address>
        <contact>02 8971 9101</contact>
        <openingHours>
            <weekday>Mon - Fri: 6:00 to 14:30</weekday>
            <weekend>Sat-Sun: 7:00 to 15:00</weekend>
        </openingHours>
    </branch>
</branches>
